credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "Credentials for git"
          id: "802db27f-c03c-411a-9e5b-0ed30bf9c968"
          password: "{AQAAABAAAAAQtB0M7aAZtb+jL0bmVU1Pq0L27svSkIu0F2Plnx3HYRs=}"
          scope: SYSTEM
          username: "git@git.com"
      - aws:
          accessKey: "AKIATSMVQX4KXUYQGMWR"
          description: "aws-jenkins-demo"
          id: "aws-jenkins-demo"
          scope: GLOBAL
          secretKey: "{AQAAABAAAAAwuSEOOOAEp9BBMOphJ+4YEBVd4Pi1elWa1d8gcBTkdTVMbEco0tsDoNSOr4vRs+VS2nI6RWgYMTIzMMjQGwb3lw==}"
      - aws:
          accessKey: "AKIATSMVQX4KXUYQGMWR"
          description: "jenkins-aws-cred"
          id: "jenkins-aws-cred"
          scope: GLOBAL
          secretKey: "{AQAAABAAAAAwjJPIoK1lwxlCVQBtWOkxpLyEtrKVou1/P1W/DbYd+eYuKr0A4k9ZpajytzDR9m+n5U0+SO2fNi5I06iEnfqzcQ==}"
      - gitHubApp:
          apiUri: "https://api.github.com"
          appID: "370126"
          description: "DevopsOrganise"
          id: "DevopsOrganise"
          privateKey: "{AQAAABAAAAawOgIFICQPKNLqs9OT9UzLJXLas+skqEexA5PZScZUYrXuVrz1gjj1qPob/L06T8dl0gKOVMDSkFRoZW0ZRYkBZaAOwnr0Ac/0lGSJpjYuGQwWFyxlpHSVNlUXZ92QGMw5SLQSWXcu/30SBPbmzpJsvxG39SU4BR7nckKQJ6lTOAPgx7h0zH6hjjmhPQh3yLncBLtI3ESdJidvAyLZ4GjIgDVL3vr9frCFpA7ysuMYxKZulOo5GL6flCgPPyx+PtpbMdKxMSfaEkW+ZT5/F8dcMFlhvnA99Um6mDrjHhsb8Hq6gLVA0PB+xy4YV88an50iNBXtu9f0FXPk4qTlV0Et174WIwnuNAM6CJQed0AsBZc1NSDqRGfFLBCVHeq/y4oAabCsQAq09cn8hq+T0vHN6DLsH5l+gUNjR8Dt3pRPZoBjuDrZQSwn8p/hN8ygTeuPb2tP2r/YonpiWESXyASId2d4ukmCHsZbWXiOKT8kG+j+M6AVSszfw6d9Hc5O52kseDGRsWAO6kx3AP9RkJrxucSUuPwNyWlt0TpgL9cjN5s15oWqt49Vu4ujPThroHgQCkmK76Fp5p497SVd3f5Bic2sYZAgh4KM49RjHleyhasrIJ/1sTjI4Er50tYifKCS39JuS3+vdEeLWV34AAq8q54IkTrF8Uqz7d/2X6xDVnZK5XDcu2Q9WZjeaYOmcChX9zA6rBjFSNT3hGTeAj4PjpJIhZDmyzanyXy1NsC1vZ1bXAtRAksNUbZoUPphrV2miT/c+dwCC81uKPkBbpbVctchSFHXNldTJ08PcwBY/BaaMVenecvb7MVFhbeYtehQWNL/+ByTESIIwFN/rA/9kU3/SpcAbKTPChRJIRDSMoEveUEhZ36iSpihzhpcs4d6oKvFCPVmlkk1JdV5K5HsHd5SAIlsfKgpdhuLXoz08XTKciimsnUWktRWl3AbH1AyF0IcxaUe0dSqFqNh7sMJzxXluKIjVfvPnNRIEYWi3HNqcE9VE68gI+KHjcZCZ8iamp8E0htgqqCD7TaDx3jkv2WuWcwFajdl3LhmRkyQ3Qm146qLEfbMvkAlK2WQT7+qdEBUtXfs307yRCpvcHnLSlhfYA5rHnAKhsSf80XdBkR/96JKnXW8TdQADwbvxgOTVmtJwOMpcY9Crz1t9NTgzaUNEEqFMjfTx185625bq/z5keqXALEDqepCQ+JkBwpXF3+MPr6lHV2S1hTmy5A6PBKX9uSwRCDSo0NJqiBflj5dmyfXwK/sWeHEEBy9djMp6/D2ngwiYUqr+nERojDldNukYnAeozpbk2NFZFjiwFpoZVwDBv1QvxgMMF4RnLNLeDrB3A31uUlbIXXSFutQmQ24/843pELYRtaGS0Vyu7AF1lvjAxC1hgCDZVLBCQhpTs8bpZsztz701yUT0TdL0gzHkICxQo9nHmShadWu7/H1A4WQ/f4IhTRnZr9Q+1nc//GYFsd1AP/SclvR2bTAUCQBPp091wc/LjxfDTvvxIWXB4XMQjVbV8eSP32Y8svvFEUjNJmRrK0nOXdQvgnhLSHVzVwnupLmZI3dM8Ou96SmY7xFYESBU15v/fzJeWerrj43mT+fTjhuGXevkLAn0PJReGIgcJNU/obhP+kctA+qD/nWvPjeDJxGZlEuIfnpwsxCLVUiF1iPh6vBO2hFyeKO4RYFt0D3TG65gXPB2jp8R4CNKWLhveVtkkODriE+fVFO4VT6f9FyyBuz5/Lm7oHQPwsOEplqXOf1SeMtgOb0dNUnZwY6PrA5PFkxF7HWKCnSBfVwkA/dlieOkJrue1vgAYvd3gbhpwbASeyUIsU4fev6SZ/YIcjwF5aND0kCUVDsgRzSqtb2I+K+x9xq7zSi+9F+bViLxkPj/zYOABmU/vWlC8qvUGEZCojlzKg9kOYVhF4axTfxBv8PPYwzgPvzMaulprRlsds0YxWRqBBNs6ihM3biPX/8NgAN5hTBbW/yMN9MlCfKRCCvlBrUdTwPlIy0KMPTKp/E2WaeVhKBAjIlHPzkCvj3zkcicBZU62QIsd+wl0O8U9qI5LNuakqlZF4F6SRPrwRX3nilkIPlHbsV/K4+Qq5M1y/liOdp4IZOgaZElXGyFn3XvkLPpBUIzk9WuPbo5d4E+GxZNO4lNSiIex06/hC/nQxf/vBMtWzwQd8vZ8SJekoC1jGZViMOd7bI/TN3w4BcHGyVKgTWyflA1tEVZ4wJhA1PHzkRz4W1U0WPbNo7q5mluTLclCDs2CJVJyNHhAqsrNEe2qbwNNU4NvSukbKpAEGrtpJk}"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
  - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 3
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
        properties:
        - "apiToken"
        - "mailer"
        - "favorite"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - "experimentalFlags"
  slaveAgentPort: 50000
  systemMessage: "Jenkins configured automatically by Jenkins\r\n\r\n"
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  copyartifact:
    mode: PRODUCTION
  envInject:
    enableLoadingFromMaster: false
    enablePermissions: false
    hideInjectedVars: false
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        enableCache: false
        manageHooks: false
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  enrichedSummaryConfig:
    enrichedSummaryEnabled: false
    httpClientDelayBetweenRetriesInSeconds: 1
    httpClientMaxRetries: 3
    httpClientTimeoutInSeconds: 1
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
    endpoints:
    - apiUri: "https://api.github.com"
      name: "GithubEnterprise"
  gitHubPluginConfig:
    configs:
    - manageHooks: false
      name: "Github"
    hookUrl: "http://ec2-3-83-95-194.compute-1.amazonaws.com:8080/github-webhook/"
  injectionConfig:
    allowUntrusted: false
    checkForBuildAgentErrors: false
    enabled: false
    enforceUrl: false
    injectCcudExtension: false
    injectMavenExtension: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://ec2-3-83-95-194.compute-1.amazonaws.com:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pluginImpl:
    enableCredentialsFromNode: false
  pollSCM:
    pollingThreadCount: 10
  prismConfiguration:
    theme: PRISM
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  upstream:
    globalUpstreamFilterStrategy: UseOldest
  warningsParsers:
    consoleLogScanningPermitted: false
tool:
  dotNetConfiguration:
    buildAllowed: true
    cleanAllowed: true
    listPackageAllowed: true
    nuGetDeleteAllowed: true
    nuGetLocalsAllowed: true
    nuGetPushAllowed: true
    packAllowed: true
    publishAllowed: true
    restoreAllowed: true
    telemetryOptOut: true
    testAllowed: true
    toolRestoreAllowed: true
  dotnetsdk:
    installations:
    - properties:
      - installSource:
          installers:
          - installDotNetSDK:
              label: "dotnet"
              release: "3.1.32"
              sdk: "3.1.426"
              url: "https://download.visualstudio.microsoft.com/download/pr/79f1cf3e-ccc7-4de4-9f4c-1a6e061cb867/68cab78b3f9a5a8ce2f275b983204376/dotnet-sdk-3.1.426-linux-arm64.tar.gz"
              version: ".NET Core 3.1"
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "Maven"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.9.4"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  nodejs:
    installations:
    - name: "nodes"
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "20.5.1"
              npmPackagesRefreshHours: 72
